---
- block:

  - name: Create system account for running crawler.
    user:
      name: "{{ fpsd_crawler_system_account }}"
      system: yes

  - name: Create a system group for running crawler.
    group:
      name: "{{ fpsd_crawler_system_account }}"
      system: yes

  - name: Add users to system group for running crawler.
    user:
      append: yes
      groups: "{{ fpsd_crawler_system_account }}"
      name: "{{ item }}"
    with_items: "{{ fpsd_database_usernames }}"

  - name: Create project directory.
    file:
      path: "{{ fpsd_crawler_project_directory }}"
      state: directory
      owner: "{{ fpsd_crawler_system_account }}"
      group: "{{ fpsd_crawler_system_account }}"
      mode: "0770"
    when: fpsd_crawler_clone_git_repo == true

  - name: Clone git repository.
    become_user: "{{ fpsd_crawler_system_account }}"
    git:
      repo: "{{ fpsd_crawler_git_repo_url }}"
      dest: "{{ fpsd_crawler_project_directory }}"
      force: yes
    # Under vagrant the project will be mounted as a shared directory,
    # so no need to clone it. Deploying to prod, however, means we'll need
    # to pull, so check the boolean var for toggling cloning functionality.
    when: fpsd_crawler_clone_git_repo == true

  - name: Ensure repository logging folder is {{ fpsd_crawler_system_account }} group writeable.
    file:
      path: "{{ fpsd_crawler_project_directory}}/fpsd/logging"
      owner: "{{ fpsd_crawler_system_account }}"
      group: "{{ fpsd_crawler_system_account }}"
      mode: "0770"

  - name: Populate config.ini.
    template:
      src: fpsd.ini.j2
      dest: "/etc/fpsd.ini"
      owner: "{{ fpsd_crawler_system_account }}"
      group: "{{ fpsd_crawler_system_account }}"
      mode: "0660"
      force: no

  - name: Install crawler pip dependencies.
    pip:
      executable: pip3
      state: latest
      requirements: "{{ fpsd_crawler_project_directory }}/fpsd/requirements/requirements.txt"

  - name: Create GOPATH.
    file:
      path: "{{ fpsd_gopath }}"
      state: directory
      owner: "{{ fpsd_crawler_system_account }}"
      group: "{{ fpsd_crawler_system_account }}"
      mode: "0770"

  - name: Set GOPATH environment variable in /etc/bashrc.
    lineinfile:
      line: "export GOPATH='{{ fpsd_gopath }}'"
      regexp: '^export GOPATH='
      dest: "/etc/bash.bashrc"
      mode: "0644"

  - name: Add GOPATH to PATH in /etc/bashrc.
    lineinfile:
      line: 'export PATH="${PATH}:${GOPATH}"'
      regexp: '^export PATH='
      dest: "/etc/bash.bashrc"
      mode: "0644"

  - name: Fetch Wa-kNN with `go get`.
    become_user: "{{ fpsd_crawler_system_account }}"
    command: go get -u {{ fpsd_wa_knn_repo }}
    environment:
      GOPATH: "{{ fpsd_gopath }}"
    register: go_get_result
    # TODO: remove this line after fixing the go-knn Go package s.t. the
    # necessary binaries are (re-)built upon calls to `go get`.
    failed_when: '"no buildable Go source files" not in go_get_result.stderr'

  become: true
