---
# Isolates the config tasks into logical groups, in case the
# config should be broken out across multiple hosts. Vars are shared
# across all of these tasks (e.g. the crawler service needs database
# credentials), so bundling them all within the same role.

- include: set-db-environment-variables.yml
  when: fpsd_database_configure_credentials == true
  tags: database

- include: configure-databases.yml
  when: fpsd_database_initialize_local_db == true
  tags: database

- block:
  - include: packages.yml
    tags: packages
  - include: configure.yml
    tags: configure
  - include: download-verify-tbb.yml
  - include: download-verify-tor.yml
  - include: build-install-tor.yml
  - include: install-systemd-unit.yml
    tags: systemd
  when: fpsd_crawler_configure_service == true
