---
- name: Create the PostgreSQL password file for database connection.
  become: yes
  template:
    src: pgpass_conf.j2
    dest: "/home/{{ item }}/.pgpass"
    mode: "0600"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ fpsd_database_usernames }}"

- name: Set the database environment variables in global bashrc.
  become: yes
  lineinfile:
    line: 'export {{ item.key }}={{ item.value }}'
    regexp: '^export {{ item.key }}='
    dest: "/etc/bash.bashrc"
    mode: "0644"
  when: item.key != 'PGPASSWORD' # Don't write password to world-readable file.
  with_dict: "{{ fpsd_database_psql_env }}"
